"""Runtime configuration for the CollabBoard backend."""

from __future__ import annotations

APP_NAME = "CollabBoard Backend"

HOST = "127.0.0.1"
PORT = 8000

LOG_LEVEL = "INFO"

USER_JOIN_GRACE_SECONDS = 30
USER_JOINED_IDLE_SECONDS = 60
USER_ACTIVE_IDLE_SECONDS = 180
USER_IDLE_TIMEOUT_SECONDS = 180
USER_LEFT_DISCONNECT_SECONDS = 5

ROOM_PENDING_INIT_TTL_SECONDS = 300
ROOM_IDLE_TTL_SECONDS = 60

TIMESTAMP_TOLERANCE_SECONDS = 30
MESSAGE_MAX_BYTES = 1_048_576
DEDUP_WINDOW_SECONDS = 300

RATE_LIMIT_MESSAGES_PER_SECOND = 100
ROOM_RATE_LIMIT_EVENTS_PER_SECOND = 1000

WEBSOCKET_READ_TIMEOUT_SECONDS = 60
WEBSOCKET_SEND_TIMEOUT_SECONDS = 3
WEBSOCKET_CLOSE_TIMEOUT_SECONDS = 2

MAINTENANCE_INTERVAL_SECONDS = 1

# Clear canvas requires unanimous consent (clear_propose / clear_vote)
CLEAR_PROPOSAL_TTL_MS = 120_000

# Text / LaTeX annotations (annotation message type)
ANNOTATION_CONTENT_MAX_CHARS = 2_000
ANNOTATION_FONT_SIZE_MIN = 8
ANNOTATION_FONT_SIZE_MAX = 72
